[Allpix]
number_of_events = 100
detectors_file = "geometry.conf"
random_seed = 123456789

[GeometryBuilderGeant4]

[DepositionPointCharge]
source_type = "point"
model = "spot"
position = 7015um 7015um 950um
spot_size = 110um
number_of_charges = 100000  

[ElectricFieldReader]
model="constant"
bias_voltage = -800V
output_plots = 1

[GenericPropagation]
temperature = 300K
charge_per_step = 25
mobility_model = "constant"
mobility_electron = 1050cm*cm/V/s
mobility_hole = 104cm*cm/V/s
propagate_holes = 0
propagate_electrons = 1
integration_time = 300ns
output_plots = 1

[PulseTransfer]


[DefaultDigitizer]
output = "low_noise"
threshold = 1e
electronics_noise = 100e
output_plots = 1
output_plots_scale = 150ke

[DefaultDigitizer]
output = "high_noise"
threshold = 1e
electronics_noise = 500e
output_plots = 1
output_plots_scale = 150ke

[DetectorHistogrammer]
input = "low_noise"
max_cluster_charge = 150ke
granularity = 256, 256

[DetectorHistogrammer]
input = "high_noise"
max_cluster_charge = 150ke
granularity = 256, 256
output_plots = 1
